instances:
  - instance_name: acl-lab
    instance_type: t2.micro
    image_id: ami-053b0d53c279acc90

buckets:
  - bucket_name: sarmatool-bucket
    region: us-east-1

resources:
  - type: iam_user
    user_name: lilo-user
  - type: iam_role
    role_name: lilo-role

Resources:
  MyRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: lilo-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: liloPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: arn:aws:s3:::my-bucket/*
